name       : xfce4-pulseaudio-plugin
version    : 0.4.7
release    : 1
source     :
    - https://archive.xfce.org/src/panel-plugins/xfce4-pulseaudio-plugin/0.4/xfce4-pulseaudio-plugin-0.4.7.tar.bz2 : 50dd090771441cd7e300e764a1bc48435ace4c3ebaa1bdd8490b4095f3968e2c
license    : GPL-2.0-or-later
component  : desktop.xfce
summary    : Pulseaudio plugin for the Xfce4 panel.
description: |
    Pulseaudio plugin for the Xfce4 panel.
builddeps  :
    - pkgconfig(exo-2)
    - pkgconfig(libcanberra)
    - pkgconfig(keybinder-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(libpulse)
    - pkgconfig(libxfce4panel-2.0)
    - pkgconfig(libxfce4ui-2)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
